modules:
  - ./loadshift-bench
  - ./loadshift-camunda-7
  - ./loadshift-camunda-8
  - ./loadshift-camunda-8-stream
  - ./loadshift-core
  - ./loadshift-demo
  - ./loadshift-local
  - ./loadshift-micrometer
  - ./loadshift-otel
  - ./loadshift-sqlite
  - ./loadshift-web
  - ./scripts/deps
  - ./scripts/engine
  - ./scripts/examples
